pipeline{
    agent any
    stages{
        stage('Checkout'){
            sh 'sleep 5'
        }
        stage('Build'){
            sh 'sleep 5'
        }
        stage('Test'){
            sh 'sleep 5'
        }
        stage('Deploy'){
            sh 'sleep 5'
        }
    }
}